// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using EndToEnd.Data.EndToEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EndToEndDB.Data.EndToEnd
{
    public partial class EndtoEndContext : DbContext
    {
        public EndtoEndContext()
        {
        }

        public EndtoEndContext(DbContextOptions<EndtoEndContext> options)
            : base(options)
        {
        }

        public virtual DbSet<WeatherForecast> WeatherForecast { get; set; }
        public virtual DbSet<Memories> Memories { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<WeatherForecast>(entity =>
            {
                entity.Property(e => e.Date).HasColumnType("datetime");

                entity.Property(e => e.Summary).HasMaxLength(50);

                entity.Property(e => e.UserName).HasMaxLength(50);
            });
            modelBuilder.Entity<Memories>(entity =>
            {
                entity.Property(e => e.memDate).HasColumnType("datetime");

                entity.Property(e => e.memText).HasMaxLength(5000);

                entity.Property(e => e.UserName).HasMaxLength(50);
               
            });
            OnModelCreatingPartial(modelBuilder);
        }


        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}